### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by rajikaimal** [cloudspex/cloudAI#11]
Hi,

I'm a maintainer of [NodeCloud ](https://github.com/cloudlibz/nodecloud) library (which you might be well aware of at this point :) ) under SCoRe lab.

I and maintainers of NodeCloud have recently observed that your project is following our standards and surprisingly the exact the same code snippets. For reference, I've included the following comparison.

CloudAI: Folder structure

![cloud-ai-folder](https://user-images.githubusercontent.com/8940086/45919727-bb91fe80-beb7-11e8-9db9-30752ee36a6b.PNG)

NodeCloud: Folder structure

![nodecloud-ai-folder](https://user-images.githubusercontent.com/8940086/45919731-c6e52a00-beb7-11e8-9941-2b41ffb2cdcc.PNG)

CloudAI: Core

![cloud-ai-core](https://user-images.githubusercontent.com/8940086/45919738-d82e3680-beb7-11e8-872e-db9c96bcbcd4.PNG)

NodeCloud: Core

![nodecloud-core](https://user-images.githubusercontent.com/8940086/45919740-e2503500-beb7-11e8-9d18-930575e4f1e5.PNG)

CloudAI provider code:

![cloud-ai-providers](https://user-images.githubusercontent.com/8940086/45919744-ed0aca00-beb7-11e8-96b3-045848e9028e.PNG)

NodeCloud provider code:

![nodecloud-providers](https://user-images.githubusercontent.com/8940086/45919746-f3994180-beb7-11e8-8824-cd4cf824b004.PNG)

It's quite evident that the two projects are similar and CloudAI is using our standards and code snippets.

While copying is not an issue since NodeCloud is under Apache 2.0, it is not ethical to just copy and paste code snippets. (In this case it's not just snippets). 

Please refer the following to learn how to give credits.

https://opensource.stackexchange.com/questions/5143/how-to-mark-a-copied-apache-v2-piece-of-code

Hope you'll be much more responsible in the future as this affects your public image as open source developers.

Peace 🤞

**Comment by rajikaimal** [comment]
cc: @rehrumesh

**Comment by Akayeshmantha** [comment]
Hey rajika yes we also trying to do some kind of a cloud provider comparison but on ai services.And yes we went through your code base as it was great and also its more similar to the problem that we address.And yes when movig forward will give the credits and move forward.And sorry for the inconvineince happened.As of now we refered few repos to identify what is the best code pattern to follow. 😀
